server.port=8081
spring.application.name=user-service

# Connexion PostgreSQL (Base de données 'users_db')
spring.datasource.url=jdbc:postgresql://localhost:5432/users_db
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update

# Configuration JWT (Secret partagé et durée de validité 24h)
jwt.secret=MaCleSecreteCommunePartageeEntreLesMicroservices123456789!
jwt.expiration-ms=86400000
