name: Local
variables:
  - name: userServiceUrl
    value: http://localhost:8081
    enabled: true
    secret: false
  - name: gameServiceUrl
    value: http://localhost:8080
    enabled: true
    secret: false
